### ISSUE TITLE
Allow config %variable% to use in routes

### ISSUE THREAD

**Issue by gander** [flint/flint#32]
Can you add support `%variable%` to config routing ? I suspect that it's not so easy, because I was looking for this solution. Because I did not want to create my own Loader, I gave up and my code will solve this little ugly:

``` php
$app['routing.loader'] = $app->share(
    $app->extend('routing.loader',
        function (DelegatingLoader $loader, Application $app) {
            return new AppRoutingLoader($loader, $app);
        }
    )
);
```

``` php
// AppRoutingLoader::load()
$collection = $this->loader->load($resource, $type);
foreach ($collection->all() as $route) {
    $fields = unserialize($route->serialize());

    array_walk_recursive($fields, function (&$value) {
        $value = $this->app['config.normalizer']->normalize($value);
    });

    $route->unserialize(serialize($fields));
}
return $collection;
```

Can you ?

**Comment by henrikbjorn** [comment]
Guess we can do something like https://github.com/symfony/framework-bundle/blob/master/Routing/Router.php#L87

**Comment by gander** [comment]
Exactly the point. Flint is very nice, and it would be even better, definitely.
